name: Example builds

on:
  push:
    branches: ['main', 'master', 'releases/*']
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
        julia-arch: [aarch64]
    
    steps:
      - uses: actions/checkout@v3.0.0

      - name: "Install dependencies"
        run: |
          npm install
          npm run build
          npm run pack

      - name: "Set up Julia"
        id: setup-julia
        uses: ./
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - run: julia --version
      - run: julia --compile=min -O0 -e 'import InteractiveUtils; InteractiveUtils.versioninfo()'
